spring:
  application.name: ms-alunos
  datasource:
    url: jdbc:mysql://localhost:3306/msalunos?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

feign:
  client:
    config:
      default:
        connect-timeout: 600000
        read-timeout: 600000

info:
  name: ${spring.application.name}
  description: Api de Cadastro de Alunos
  version: 0.0.1

management:
  metrics:
    tags:
      application: ${spring.application.name}
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true
      resilience4j:
        circuitbreaker:
          calls: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 8
      minimumNumberOfCalls: 4
  instances:
    DISCIPLINES_CB:
      baseConfig: default